image: node:20

pipelines:
  default:
    - step:
        name: Build React App
        caches:
          - node
        script:
          - npm ci
          - npm run build
        artifacts:
          - dist/**
