image: node:20

pipelines:
  default:
    - step:
        name: Build and Deploy React App
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - yarn build
          - echo "Build completed successfully"
          - ls -la dist/
        artifacts:
          - dist/**
